const menu=document.querySelector('.menu-toggle'),links=document.querySelector('.nav-links');
menu?.addEventListener('click',()=>{const open=links.classList.toggle('open');menu.setAttribute('aria-expanded',open)});
document.querySelectorAll('.nav-links a').forEach(a=>a.addEventListener('click',()=>links.classList.remove('open')));

const productData={
'Antistatic PVC Mat':{cat:'ESD & CONSUMABLES',intro:'Static-dissipative bench protection for controlled electronics workspaces.',features:['Helps reduce static charge at the workstation','Suitable for ESD-controlled benches and assembly areas','Easy to integrate into existing workstations'],visual:'mat'},
'Epoxy Flooring':{cat:'ESD & CONSUMABLES',intro:'Durable flooring designed for static-conscious industrial environments.',features:['Continuous floor protection for controlled areas','Built for demanding industrial workflows','Designed as part of a complete ESD-control system'],visual:'floor'},
'ESD Wrist Strap':{cat:'ESD & CONSUMABLES',intro:'Essential operator grounding for handling sensitive electronic components.',features:['Designed for operator grounding','Ideal for ESD workstations','Simple everyday workstation protection'],visual:'strap'},
'Antistatic Gloves':{cat:'ESD & CONSUMABLES',intro:'Comfortable handling protection for sensitive components and assemblies.',features:['Helps minimise static-related handling risk','Suitable for precision component work','Comfort-focused everyday protection'],visual:'glove'},
'ESD Chair':{cat:'ESD & CONSUMABLES',intro:'Ergonomic seating designed for static-controlled work zones.',features:['Supports controlled workstation environments','Ergonomic industrial seating concept','Pairs with ESD flooring and workstation systems'],visual:'chair'},
'Sticky Mat':{cat:'ESD & CONSUMABLES',intro:'Entrance and clean-area matting for particle-control workflows.',features:['Helps capture dust and particles','Useful at controlled-area entrances','Simple layered workplace hygiene solution'],visual:'sticky'},
'Antistatic Apparel':{cat:'ESD & CONSUMABLES',intro:'Protective garments for ESD-sensitive production environments.',features:['Designed for controlled electronics areas','Supports operator-focused ESD practices','Pairs with grounding and workstation controls'],visual:'apparel'},
'Antistatic Cap':{cat:'ESD & CONSUMABLES',intro:'Headwear designed for controlled electronics production areas.',features:['Supports controlled-area apparel requirements','Lightweight operator accessory','Complements antistatic garments'],visual:'cap'},
'Wrist Bands':{cat:'ESD & CONSUMABLES',intro:'Practical operator grounding accessories for ESD workstations.',features:['Convenient workstation grounding accessory','Designed for regular operator use','Part of a broader grounding strategy'],visual:'band'},
'Antistatic PU Gloves':{cat:'ESD & CONSUMABLES',intro:'Grip and handling comfort for delicate component work.',features:['Useful for precision handling','Designed around grip and operator comfort','Supports static-conscious assembly workflows'],visual:'pu'},
'Surface Resistivity Meter':{cat:'ESD & CONSUMABLES',intro:'Measurement equipment for checking surface resistance and static-control performance.',features:['Supports routine surface verification','Useful for ESD programme checks','Helps teams document control conditions'],visual:'meter'},
'Wristband & Footwear Tester':{cat:'ESD & CONSUMABLES',intro:'Fast verification equipment for operator grounding systems.',features:['Checks wristband and footwear grounding','Useful at controlled-area entrances','Supports routine operator verification'],visual:'tester'},
'Antistatic Bubble Roll':{cat:'ESD & CONSUMABLES',intro:'Protective packaging material for ESD-sensitive components.',features:['Cushioning for component protection','Designed for ESD-conscious packaging','Useful for storage and transport workflows'],visual:'bubble'},
'Touch Me Pad':{cat:'ESD & CONSUMABLES',intro:'Convenient static-control accessory for operator discharge.',features:['Simple operator interaction point','Useful at workstations and entrances','Complements a broader ESD-control programme'],visual:'touch'},
'Insulation Mat':{cat:'ESD & CONSUMABLES',intro:'Robust matting for defined industrial work areas.',features:['Durable industrial surface solution','Useful for defined workspace zones','Designed to integrate with workplace safety planning'],visual:'insulation'},
'Conductive Super Bins':{cat:'STORAGE SOLUTIONS',intro:'Organised static-safe component storage for production and assembly areas.',features:['Keeps components organised and accessible','Conductive storage concept for ESD-sensitive parts','Ideal for shelves, benches and line-side storage'],visual:'bin'},
'ESD I Type Rack':{cat:'STORAGE SOLUTIONS',intro:'Modular rack storage for efficient controlled workspaces.',features:['Helps maximise organised storage','Designed for ESD-conscious environments','Useful for component and material organisation'],visual:'rack'}};

const modal=document.createElement('div');modal.className='product-modal';modal.innerHTML=`<div class="modal-backdrop" data-close></div><div class="modal-panel" role="dialog" aria-modal="true" aria-label="Product details"><button class="modal-close" aria-label="Close">×</button><div class="modal-visual"><div class="modal-visual-art"></div><span class="modal-number"></span></div><div class="modal-content"><small class="modal-cat"></small><h2 class="modal-title"></h2><p class="modal-intro"></p><div class="modal-rule"></div><h3>Key highlights</h3><ul class="modal-features"></ul><button class="modal-enquire">Enquire about this product ↗</button></div></div>`;document.body.appendChild(modal);
const modalEls={title:modal.querySelector('.modal-title'),cat:modal.querySelector('.modal-cat'),intro:modal.querySelector('.modal-intro'),features:modal.querySelector('.modal-features'),art:modal.querySelector('.modal-visual-art'),number:modal.querySelector('.modal-number')};
function openProduct(name){const d=productData[name];if(!d)return;modalEls.title.textContent=name;modalEls.cat.textContent=d.cat;modalEls.intro.textContent=d.intro;modalEls.features.innerHTML=d.features.map(x=>`<li>${x}</li>`).join('');modalEls.art.className=`modal-visual-art modal-${d.visual}`;const card=[...document.querySelectorAll('.product-card')].find(x=>x.dataset.name===name.toLowerCase());modalEls.number.textContent=card?.querySelector('.product-image>span')?.textContent||'';modal.classList.add('open');document.body.classList.add('modal-open');modal.querySelector('.modal-close').focus()}
function closeProduct(){modal.classList.remove('open');document.body.classList.remove('modal-open')}
modal.addEventListener('click',e=>{if(e.target.matches('[data-close],.modal-close'))closeProduct()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeProduct()});
modal.querySelector('.modal-enquire').addEventListener('click',()=>{const name=modalEls.title.textContent;const msg=`Hello Static Safety Solutions, I am interested in ${name}. Please share specifications, availability and a quotation.`;window.open(`https://wa.me/?text=${encodeURIComponent(msg)}`,'_blank','noopener')});

document.querySelectorAll('.product-card').forEach(card=>{const info=card.querySelector('.product-info');const name=card.querySelector('h3')?.textContent;if(name&&productData[name]){const view=document.createElement('button');view.className='view-details';view.textContent='View details';view.addEventListener('click',()=>openProduct(name));info?.insertBefore(view,info.querySelector('.enquire'));}});

let activeFilter='all';const cards=[...document.querySelectorAll('.product-card')];
function applyFilters(){const q=(document.querySelector('#productSearch')?.value||'').trim().toLowerCase();cards.forEach(card=>{const categoryOK=activeFilter==='all'||card.dataset.category===activeFilter;const searchOK=!q||card.dataset.name.includes(q);card.classList.toggle('no-match',!(categoryOK&&searchOK));});}
document.querySelectorAll('.filter').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));btn.classList.add('active');activeFilter=btn.dataset.filter;applyFilters()}));
document.querySelector('#productSearch')?.addEventListener('input',applyFilters);

document.querySelectorAll('.enquire').forEach(btn=>btn.addEventListener('click',()=>{const product=btn.dataset.product;const msg=`Hello Static Safety Solutions, I am interested in ${product}. Please share details, availability and a quotation.`;window.open(`https://wa.me/?text=${encodeURIComponent(msg)}`,'_blank','noopener')}));
const form=document.querySelector('#enquiryForm');form?.addEventListener('submit',e=>{e.preventDefault();const d=new FormData(form);const msg=`Hello Static Safety Solutions,\n\nName: ${d.get('name')}\nCompany: ${d.get('company')||'Not provided'}\nPhone: ${d.get('phone')}\nRequirement: ${d.get('message')}`;window.open(`https://wa.me/?text=${encodeURIComponent(msg)}`,'_blank','noopener')});

const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.08});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
applyFilters();